### ISSUE TITLE
Is there missing code for generating the text.json file during inference?

### ISSUE THREAD

**Issue by backyardknights** [Nathan-Li123/SMOTer#9]
![1](https://github.com/user-attachments/assets/0b957959-8aa3-4cb8-a574-0b6c4bf8579b)
![WQ~ 2@KHLOKO6 P(LQ)XD1J](https://github.com/user-attachments/assets/9d99eeef-6d02-4b76-b43e-9033efd85925)
![~$%U1O_8%7X R JQ)1OBPVD](https://github.com/user-attachments/assets/7f644f14-4564-40e3-aca7-a2b5c0c3f433)
I used an RTX 3090 for training and obtained my own model_0059999.pth. However, whether I use my model or the one you provided, I encounter the same issue as described in issue #5. 
The only output I get during inference is output/SMOTer/BYTE_BENSMOT_FPN/inference_bensmot_val/instances_predictions.pth. I’m wondering if the code uploaded to GitHub might be missing the part that generates files like summary_results.json. Could it be that this functionality should be implemented in the BenSMOTEvaluator class in smoter/evaluation/bensmot_evaluation.py?

**Comment by Nathan-Li123** [comment]
Apologies for the delayed response. This issue has troubled us for a long time and was just resolved. It occurred because we had made modifications to the Detectron2 code but did not push them to GitHub. The updated Detectron2 code has now been added to the repository. You can use the inference_on_dataset function from detectron2/detectron2/evaluation/evaluator.py to replace the corresponding function in the original Detectron2 at the same location, which should resolve the issue.

**Comment by backyardknights** [comment]
Thank you for your response. I performed inference separately using the modified inference_on_dataset function and the updated version of the entire Detectron2 you provided. However, it seems there are still some issues. The results are as follows:
![YD)2 V%D~6PC4G83Q1692SL](https://github.com/user-attachments/assets/10cc5c08-7d76-46d7-8f22-326b955f591a)

[11/20 01:30:38 d2.evaluation.evaluator]: Inference done 951/951. Dataloading: 6.6702 s/iter. Inference: 8.7141 s/iter. Eval: 0.0276 s/iter. Total: 15.4173 s/iter. ETA=0:00:00
[11/20 01:30:38 d2.evaluation.evaluator]: Total inference time: 4:03:04.823003 (15.417360 s / iter per device, on 1 devices)
[11/20 01:30:38 d2.evaluation.evaluator]: Total inference pure compute time: 2:17:23 (8.714115 s / iter per device, on 1 devices)
[11/20 01:30:42 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[11/20 01:30:42 d2.evaluation.coco_evaluation]: Saving results to ./output/SMOTer/BYTE_BENSMOT_FPN/inference_bensmot_val/coco_instances_results.json
[11/20 01:30:44 d2.evaluation.coco_evaluation]: Evaluating predictions with unofficial COCO API...
Loading and preparing results...
DONE (t=2.57s)
creating index...
index created!
[11/20 01:30:47 d2.evaluation.fast_eval_api]: Evaluate annotation type *bbox*
[11/20 01:31:06 d2.evaluation.fast_eval_api]: COCOeval_opt.evaluate() finished in 19.20 seconds.
[11/20 01:31:06 d2.evaluation.fast_eval_api]: Accumulating evaluation results...
[11/20 01:31:12 d2.evaluation.fast_eval_api]: COCOeval_opt.accumulate() finished in 5.74 seconds.
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.643
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.851
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.701
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.160
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.644
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.376
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.694
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.694
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.179
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.697
[11/20 01:31:12 d2.evaluation.coco_evaluation]: Evaluation results for bbox: 
|   AP   |  AP50  |  AP75  |  APs  |  APm   |  APl   |
|:------:|:------:|:------:|:-----:|:------:|:------:|
| 64.306 | 85.106 | 70.052 | 0.000 | 15.962 | 64.443 |

removing ./output/SMOTer/BYTE_BENSMOT_FPN/inference_bensmot_val/bensmoteval/BenSMOT-val/pred/data/
config {'USE_PARALLEL': False, 'NUM_PARALLEL_CORES': 8, 'BREAK_ON_ERROR': True, 'RETURN_ON_ERROR': False, 'LOG_ON_ERROR': '/data/zf/SMOTer/smoter/tracking/error_log.txt', 'PRINT_RESULTS': True, 'PRINT_ONLY_COMBINED': False, 'PRINT_CONFIG': True, 'TIME_PROGRESS': True, 'DISPLAY_LESS_PROGRESS': True, 'OUTPUT_SUMMARY': True, 'OUTPUT_EMPTY_CLASSES': True, 'OUTPUT_DETAILED': True, 'PLOT_CURVES': True, 'GT_FOLDER': 'datasets/bensmot', 'TRACKERS_FOLDER': './output/SMOTer/BYTE_BENSMOT_FPN/inference_bensmot_val/bensmoteval', 'OUTPUT_FOLDER': None, 'TRACKERS_TO_EVAL': None, 'CLASSES_TO_EVAL': ['pedestrian'], 'BENCHMARK': 'BenSMOT', 'SPLIT_TO_EVAL': 'val', 'INPUT_AS_ZIP': False, 'DO_PREPROC': True, 'TRACKER_SUB_FOLDER': 'data', 'OUTPUT_SUB_FOLDER': 'datasets/bensmot/seqmaps/test.txt', 'TRACKER_DISPLAY_NAMES': None, 'SEQMAP_FOLDER': None, 'SEQMAP_FILE': '', 'SEQ_INFO': None, 'GT_LOC_FORMAT': '{gt_folder}/{seq}/gt/gt{split_mark}.txt', 'SKIP_SPLIT_FOL': False, 'METRICS': ['HOTA', 'CLEAR', 'Identity']}

Eval Config:
USE_PARALLEL         : False                         
NUM_PARALLEL_CORES   : 8                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : /data/zf/SMOTer/smoter/tracking/error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : True                          
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : True                          

MotChallenge2DBox Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : datasets/bensmot              
TRACKERS_FOLDER      : ./output/SMOTer/BYTE_BENSMOT_FPN/inference_bensmot_val/bensmoteval
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : None                          
CLASSES_TO_EVAL      : ['pedestrian']                
BENCHMARK            : BenSMOT                       
SPLIT_TO_EVAL        : val                           
INPUT_AS_ZIP         : False                         
DO_PREPROC           : True                          
TRACKER_SUB_FOLDER   : data                          
OUTPUT_SUB_FOLDER    : datasets/bensmot/seqmaps/test.txt
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : None                          
SEQMAP_FILE          :                               
SEQ_INFO             : None                          
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt{split_mark}.txt
SKIP_SPLIT_FOL       : False                         
gt_set BenSMOT-val
Traceback (most recent call last):
  File "train_net.py", line 296, in <module>
    launch(
  File "/data/zf/SMOTer/detectron2/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "train_net.py", line 276, in main
    return do_test(cfg, model)
  File "train_net.py", line 129, in do_test
    results[dataset_name], summary[dataset_name], caption[dataset_name], relation[dataset_name] = inference_on_dataset(
  File "/data/zf/SMOTer/detectron2/detectron2/evaluation/evaluator.py", line 217, in inference_on_dataset
    results = evaluator.evaluate()
  File "/data/zf/SMOTer/detectron2/detectron2/evaluation/coco_evaluation.py", line 206, in evaluate
    self._eval_predictions(predictions, img_ids=img_ids)
  File "/data/zf/SMOTer/smoter/evaluation/bensmot_evaluation.py", line 209, in _eval_predictions
    track_and_eval_bensmot(
  File "/data/zf/SMOTer/smoter/evaluation/bensmot_evaluation.py", line 68, in track_and_eval_bensmot
    eval_track(out_dir + '/bensmoteval')
  File "/data/zf/SMOTer/smoter/evaluation/bensmot_evaluation.py", line 92, in eval_track
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/data/zf/SMOTer/smoter/tracking/trackeval/datasets/mot_challenge_2d_box.py", line 92, in __init__
    self.seq_list, self.seq_lengths = self._get_seq_info()
  File "/data/zf/SMOTer/smoter/tracking/trackeval/datasets/mot_challenge_2d_box.py", line 179, in _get_seq_info
    raise TrackEvalException('ini file does not exist: ' + seq + '/' + ini_file)
smoter.tracking.trackeval.utils.TrackEvalException: ini file does not exist: pcr_testing/fI-xG08zKnA_0/datasets/bensmot/BenSMOT-val/pcr_testing/fI-xG08zKnA_0/seqinfo.ini

**Comment by blauer4** [comment]
> Thank you for your response. I performed inference separately using the modified inference_on_dataset function and the updated version of the entire Detectron2 you provided. However, it seems there are still some issues. The results are as follows: ![YD)2 V%D~6PC4G83Q1692SL](https://private-user-images.githubusercontent.com/69116255/387894787-10cc5c08-7d76-46d7-8f22-326b955f591a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMzM1MzQsIm5iZiI6MTczNjMzMzIzNCwicGF0aCI6Ii82OTExNjI1NS8zODc4OTQ3ODctMTBjYzVjMDgtN2Q3Ni00NmQ3LThmMjItMzI2Yjk1NWY1OTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDEwNDcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNTAwNTgxMmQ3MGU2MTA3YjRhZWU2YzUzZjc1NzdlNzU3YjFiYWVmZGI1YTNmYmIyZDRkZjdmMTAwZGU4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ctud7riOXsq9i98x7drnkhwD0_OsM2Zrm4xCpcNYzoI)

Hi, I had the same issue but the problem is that in the dataset the seqinfo file is not included. Another thing is that the path is not properly set in the `mot_challenge_2d_box.py` file.
However, you can fix it by adding this `seqinfo` file in the dataset folder for each test sequence. 
In this case, it is quite straightforward: you sort the files by name and get the maximum value of the filename in the test folder. 

After this it will be all done, but remember to install `nltk` and download wordnet with `nltk.download('wordnet')`. 

The problem is that I cannot reproduce the same results for the tracking part, but for the semantic part I obtain similar results as reported in the paper. 
I'm trying to understand if there is something missing/wrong that I'm doing.

**Comment by 2398274582** [comment]
> > Thank you for your response. I performed inference separately using the modified inference_on_dataset function and the updated version of the entire Detectron2 you provided. However, it seems there are still some issues. The results are as follows: ![YD)2 V%D~6PC4G83Q1692SL](https://private-user-images.githubusercontent.com/69116255/387894787-10cc5c08-7d76-46d7-8f22-326b955f591a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMzM1MzQsIm5iZiI6MTczNjMzMzIzNCwicGF0aCI6Ii82OTExNjI1NS8zODc4OTQ3ODctMTBjYzVjMDgtN2Q3Ni00NmQ3LThmMjItMzI2Yjk1NWY1OTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDEwNDcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNTAwNTgxMmQ3MGU2MTA3YjRhZWU2YzUzZjc1NzdlNzU3YjFiYWVmZGI1YTNmYmIyZDRkZjdmMTAwZGU4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ctud7riOXsq9i98x7drnkhwD0_OsM2Zrm4xCpcNYzoI)
> 
> Hi, I had the same issue but the problem is that in the dataset the seqinfo file is not included. Another thing is that the path is not properly set in the `mot_challenge_2d_box.py` file.不过，您可以通过在每个测试序列的数据集文件夹中添加此`seqinfo`文件来解决这个问题。在这种情况下，方法相当简单：您按文件名对文件进行排序，然后获取测试文件夹中文件名的最大值。
> 
> 此后一切就完成了，但记得安装`nltk`并下载WordNet`nltk.download('wordnet')`.
> 
> 问题在于，我无法重现跟踪部分的相同结果，但在语义部分，我得到了与论文中报告相似的结果。我正试图弄清楚，是不是我遗漏了什么或哪里做错了。

I also cannot reach the level mentioned in the paper in terms of tracking indicators. Have you resolved this issue?
